services:

  db:
    image: ${IMAGE_DB}
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_DB}:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 5s

  seeder:
    build: ${IMAGE_SEEDER}
    restart: "no"
    depends_on:
      - db
    command: ["sh", "-c", "until nc -z -v -w30 db $$PORT_DB; do echo 'Waiting for database...'; sleep 5; done; npm run seed && touch /tmp/seed_done"]
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      HOST: ${HOST}
      SERVER_URL: ${SERVER_URL}

  back:
    depends_on:
      - seeder
    build: ${IMAGE_BACKEND}
    restart: unless-stopped
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT_BACK: ${PORT_BACK}
      PORT_FRONT: ${PORT_FRONT}
      SERVER_URL: ${SERVER_URL}
      SERVER_URL_DEV: ${SERVER_URL_DEV}
      SERVER_URL_STAGING: ${SERVER_URL_STAGING}
      SERVER_URL_PRODUCTION: ${SERVER_URL_PRODUCTION}
      HOST: ${HOST}

  adminer:
    image: ${IMAGE_ADMINER}
    restart: always
    ports:
      - "${PORT_ADMINER}:8080"

  client:
      build: ${IMAGE_FRONTEND}
      restart: unless-stopped
      ports: 
          - "${PORT_FRONT}:${PORT_FRONT}"
      command: npm run dev
      volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/index.html:/app/index.html
      - ./frontend/codegen.ts:/app/codegen.ts
      environment:
          WDS_SOCKET: 127.0.0.1
          CHOKIDAR_USEPOLLING: true
          WATCHPACK_POLLING: true
          VITE_PORT_FRONT: ${VITE_PORT_FRONT}
          VITE_PORT_BACK: ${VITE_PORT_BACK}
          VITE_PORT_TRAD: ${VITE_PORT_TRAD}
          VITE_SERVER_URL: ${VITE_SERVER_URL}
          VITE_URL_BACK: ${VITE_URL_BACK}
          VITE_TRANSLATION_SERVER_URL: ${VITE_TRANSLATION_SERVER_URL}
          VITE_IMAGE_PROGRAMME: ${VITE_IMAGE_PROGRAMME}
          VITE_IMAGE_GIF: ${VITE_IMAGE_GIF}
          VITE_SERVER_URL_DEV: ${VITE_SERVER_URL_DEV}
          VITE_SERVER_URL_DEV_APOLLO: ${VITE_SERVER_URL_DEV_APOLLO}
          VITE_SERVER_URL_STAGING: ${VITE_SERVER_URL_STAGING}
          VITE_SERVER_URL_STAGING_APOLLO: ${VITE_SERVER_URL_STAGING_APOLLO}
          VITE_SERVER_URL_PRODUCTION: ${VITE_SERVER_URL_PRODUCTION}
          VITE_SERVER_URL_PRODUCTION_APOLLO: ${VITE_SERVER_URL_PRODUCTION_APOLLO}


  translation:
    build: ${IMAGE_TRANSLATION}
    restart: unless-stopped
    ports:
      - "${PORT_TRAD}:${PORT_TRAD}"
    volumes:
      - ./translation-server:/app
    environment:
      WDS_SOCKET: 127.0.0.1
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      PORT_FRONT: ${PORT_FRONT}
      PORT_BACK: ${PORT_BACK}
      PORT_TRAD: ${PORT_TRAD} 
      SERVER_URL: ${SERVER_URL}

volumes:
  pgdata: