

volumes:
  playwright-report:
    driver: local

services:
  front:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://0.0.0.0:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      sh -c "
      npm install &&
      npm run dev
      "
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/index.html:/app/index.html:ro
      - ./frontend/codegen.ts:/app/codegen.ts:ro
    environment:
      WDS_SOCKET: 0.0.0.0
      CHOKIDAR_USEPOLLING: false
      WATCHPACK_POLLING: false

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile.e2e
    working_dir: /app
    depends_on:
      front:
        condition: service_healthy
    ports:
      - "9323:9323"
    volumes:
      - playwright-report:/app/playwright-report
    command: >
      sh -c "
      echo 'Running Playwright e2e tests...' &&
      npx playwright test
      "