# to test this docker-compose locally and not wait for push on dev branch : docker compose -f docker-compose.e2e.yml up --build --exit-code-from e2e
# to access Playwright report => go into e2e folder then run : npx playwright show-report

services:
  front:
    build: ./frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3001:3000" # External port 3001 so no conflicts with the port 3000 already running in main docker-compose.yml in client service
    command: npm run dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/index.html:/app/index.html
      - ./frontend/codegen.ts:/app/codegen.ts
    environment:
      WDS_SOCKET: 127.0.0.1
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true

  e2e:
    image: mcr.microsoft.com/playwright:v1.50.1-noble
    working_dir: /tests
    volumes:
      - ./e2e:/tests
    depends_on:
      - front
    ports:
      - "9323:9323" # port localhost:9323 for Playwright report
    command: >
      sh -c "
      echo 'Running Playwright e2e tests...' &&
      npx playwright test
      "
