name: back_unit_tests

on: 
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  back_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend  # plus besoin de remettre le chemin cd backend à chaque step

    steps:
      - name: Checkout PulseForm code
        uses: actions/checkout@v4

      - name: npm install dependencies
        run: npm i

      - name: Typescript transpile
        run: npx tsc

      - name: Run back unit tests
        run: npm test
      