name: back_unit_tests

on: 
  pull_request:
    branches: [ main, dev ]

jobs:
  back_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PulseForm code
        uses: actions/checkout@v4
      - name: npm install dependencies
        run: cd backend && npm i
      - name: Move in back and Typescript transpile
        run: cd backend && npx tsc
      - name: Run back unit tests
        run: npm test
        working-directory: ./backend