name: deploy to staging

on:
  push:
    branches: [ dev ]

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer SSH pour le serveur
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      
      # Étape 3 : Obtenir la date
      - name: Get current date
        run: |
          echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      # Étape 4 : Configurer QEMU pour la construction multiplateforme
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Étape 5 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 6 : Connexion à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      # Étape 7 : Extraire le nom du repo en minuscules
      - name: Extract repository name in lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Étape 8 : Construire et pousser l'image Docker du Backend
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_NAME }}:backend-staging
          build-args: |
            CACHEBUST=${{ github.sha }}  # Cache-busting

      # Étape 9 : Construire et pousser l'image Docker du Frontend
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_NAME }}:frontend-staging
          build-args: |
            CACHEBUST=${{ github.sha }}  # Cache-busting
      
      # Étape 10 : Construire et pousser l'image Docker du serveur de traduction
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./translation-server
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_NAME }}:translation-staging
          build-args: |
            CACHEBUST=${{ github.sha }}  # Cache-busting

      # Étape 11 : Authentifier docker sur le serveur
      - name: Authenticate Docker on the server
        run: |
          ssh -o StrictHostKeyChecking=no -p 2269 wns_student@${{ secrets.SERVER_IP }} "
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          "

      # Étape 12 : Déployer sur le vps
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p 2269 wns_student@${{ secrets.SERVER_IP }} "
            cd pulseform/staging &&
            echo 'Pulling and deploying Docker container...' &&
            docker compose -f docker-compose.yml pull &&
            docker compose -f docker-compose.yml up -d &&
            echo 'Deployment complete.'
          "
          
      # Étape 13 : Nettoyer le serveur
      - name: Clean up Docker on staging Server
        run: |
          ssh -o StrictHostKeyChecking=no -p 2269 wns_student@${{ secrets.SERVER_IP }} "
            echo 'Starting Docker cleanup...' &&
            echo 'Before cleanup:' &&
            df -h &&
            docker system prune -a --force &&
            docker image prune -a --force &&
            docker volume prune --force &&
            docker network prune --force &&
            echo 'After cleanup:' &&
            df -h &&
            echo 'Docker cleanup completed successfully.'
          "
          
  e2e_tests:
    needs: deploy_staging
    runs-on: ubuntu-latest

    steps:
      # Étape 14 : Cloner le code
      - name: Checkout the code
        uses: actions/checkout@v4

      # Étape 15 : Attendre que la staging soit déployée
      - name: Wait for staging to be ready
        run: |
          echo "Checking staging environment availability..."
          for i in {1..10}; do
            if curl --max-time 3 -sSf https://staging.052024-jaune-4.wns.wilders.dev/health; then
              echo "Staging is up! Proceeding with tests."
              exit 0
            fi
            echo "Staging not ready yet. Retrying in 5s... ($i/10)"
            sleep 5
          done
          echo "Staging did not become ready in time."
          exit 1

      # Étape 16 : Installer les dépendances
      - name: Install dependencies
        run: |
          cd e2e
          npm ci

      # Étape 17 : Installer playwright et ses dépendences et lancer les tests
      - name: Install Playwright and run tests
        run: |
          cd e2e
          npx playwright install --with-deps
          npx playwright test --reporter=html

      # Étape 18 : Charger le rapport html
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: e2e/playwright-report/

      # Étape 19 : Créer le rapport des tests e2e
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/playwright-report.json

      # Étape 20 : Afficher la liste des screenshots d'échec
      - name: Debug logs (screenshots)
        if: failure()
        run: |
          ls -l e2e/test-results/

      # Étape 21 : Créer un artifact des screenshots d'échec
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-snapshots
          path: e2e/test-results/
        