name: front_unit_tests

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]


jobs:
  front_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend  # plus besoin de remettre le chemin cd frontend à chaque step

    steps:
      - name: Checkout PulseForm code
        uses: actions/checkout@v4

      - name: remove package-lock.json and node-modules
        run: rm -rf package-lock.json node_modules

      - name: npm install dependencies
        run: npm i

      - name: Typescript transpile
        run: npx tsc

      - name: Run front unit tests
        run: npm test
    