name: front_unit_tests

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  back_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PulseForm code
        uses: actions/checkout@v4
      - name: npm install dependencies
        run: cd frontend && npm i
      - name: Move in back and Typescript transpile
        run: cd frontend && npx tsc
      - name: Run front unit tests
        run: npm test
        working-directory: ./frontend